### PR TITLE
Change the requires to salt-formulas-configuration

### PR DESCRIPTION
**Pull request by diegoakechi**
This is the virtual "provides" shared by salt and SUMA to make the
formulas works with both (not at the same time).

### CODE REVIEW

**Review by arbulu89 — APPROVED** [review]
LGTM!

**Comment by nick-wang** [comment]
@diegoakechi @arbulu89 Somehow i missed the pr and did the similar change...
I will merge it and sorry for the late.

**Comment by nick-wang** [comment]
Merged the changelogs but the git commit.
Due to i missed the pull request and did a similar change refer to the habootstrap-formula, it is hard to merge directly unless a completely rebase...

Thanks for the commit and really sorry for my miss.

**Review by nick-wang — COMMENTED** [review]
LGTM, but i changed due to miss the notification days ago...  Really sorry!

**Comment by diegoakechi** [comment]
@nick-wang  No problem at all. The most important think is to solve the problem! ;)

**Pull request closed without merging**
