### PR TITLE
add native fencing for microsoft-azure

### PR DESCRIPTION
**Pull request by yeoldegrove**
This adds the needed resources to implement native fencing on azure.

It also defines for all cloud providers the same defaults to use native fencing as https://github.com/SUSE/ha-sap-terraform-deployments/.
```
# ha-sap-terraform-deployments
grep -A5 hana_cluster_fencing_mechanism */variables.tf | grep 'variable |default'
  1:openstack/variables.tf:variable "hana_cluster_fencing_mechanism" {
  4:openstack/variables.tf-  default     = "sbd"
  8:libvirt/variables.tf:variable "hana_cluster_fencing_mechanism" {
  11:libvirt/variables.tf-  default     = "sbd"
  21:gcp/variables.tf:variable "hana_cluster_fencing_mechanism" {
  24:gcp/variables.tf-  default     = "native"
  34:azure/variables.tf:variable "hana_cluster_fencing_mechanism" {
  37:azure/variables.tf-  default     = "sbd"
  47:aws/variables.tf:variable "hana_cluster_fencing_mechanism" {
  50:aws/variables.tf-  default     = "native"
```

```
# this formula
{%- if cloud_provider == "amazon-web-services" %}
{%- set native_fencing = data.native_fencing|default(True) %}
{%- elif cloud_provider == "google-cloud-platform" %}
{%- set native_fencing = data.native_fencing|default(True) %}
{%- elif cloud_provider == "microsoft-azure" %}
{%- set native_fencing = data.native_fencing|default(False) %}
{%- endif %}

```

### CODE REVIEW

**Review by arbulu89 — CHANGES_REQUESTED** [review]
Thanks @yeoldegrove ,

Update the version in the `_service` file please

**Review by nick-wang — DISMISSED** [review]
Looks good to me, though i don't try it on Azure.
Thanks for the commits.

**Review by arbulu89 — CHANGES_REQUESTED** [review]
As commented in other similar PRs, we cannot use the grains entry here

**Comment by nick-wang** [comment]
> As commented in other similar PRs, we cannot use the grains entry here

Yes, pillar is better in this case. I didn't notice this in the review.

**Comment by yeoldegrove** [comment]
@arbulu89 now pillars are used and some documentation is available here https://github.com/SUSE/habootstrap-formula/pull/84

**Review by arbulu89 — APPROVED** [review]

**Review by arbulu89 — APPROVED** [review]

**Pull request merged**
