### PR TITLE
Add pillar examples for ha-sap-terraform-deployment project.

### PR DESCRIPTION
**Pull request by nick-wang**
These pillars only work when no customized pillars provided in
ha-sap-terraform-deployment project.
https://github.com/SUSE/drbd-formula/issues/15

### CODE REVIEW

**Comment by nick-wang** [comment]
@arbulu89 My plan is to keep the default files in `drbd-formula` and remove the same files in [ha-sap-terraform-deployments](https://github.com/SUSE/ha-sap-terraform-deployments/tree/develop) as long as the change release.
However, i think we will need to keep the ability to use customized pillar file in `ha-sap-terraform-deployments`, since it is much easier to change there than create a new formula package. The logic code of this will be changed in `ha-sap-terraform-deployments`. how do think of the plan?

**Comment by nick-wang** [comment]
Refer to the change in ha-sap-terraform-deployment https://github.com/SUSE/ha-sap-terraform-deployments/pull/547

Only use these file when `drbd.sls`, `cluster.sls` and `notify-split-brain-haclusterexporter-suse-metric.sh` not exist.

**Review by arbulu89 — CHANGES_REQUESTED** [review]
@nick-wang Honestly, I don't like these changes. I don't want to have references here to `ha-sap-terraform-deployments` project.

What I simply wanted, is to ship here the cluster resources file for a DRBD/NFS usage case, and maybe the split brains script. But in fact, I think that this 2nd should go in the `ha-cluster-exporter` (it's only used by the exporter). @stefanotorresi @MalloZup What do you think about this 2nd comment?

Having the documentation and the pillar files here for the other project, doesn't make much sense neither in my opinion. The pillar example should belong to the `ha-sap-terraform-projects`.

In `saphanabootstrap-formula` and `sapnwbootstrap-formula` we ship the cluster_resources.j2, and that's it

**Comment by nick-wang** [comment]
@arbulu89 hmm... so i misunderstood your idea on https://github.com/SUSE/drbd-formula/issues/15
I have already put the usage example in `drbd-formula` with/without a pacemaker, do you think the [drbd nfs j2 template file](https://github.com/SUSE/drbd-formula/blob/master/examples/with_pacemaker/drbd_with_nfs_crm.j2) is enough?

If so, we can close this and https://github.com/SUSE/ha-sap-terraform-deployments/pull/547

**Comment by stefanotorresi** [comment]
> What I simply wanted, is to ship here the cluster resources file for a DRBD/NFS usage case, and maybe the split brains script. But in fact, I think that this 2nd should go in the `ha-cluster-exporter` (it's only used by the exporter). @stefanotorresi @MalloZup What do you think about this 2nd comment?

The split brain script is something that is executed by drbd via the configuration provided in this formula; the exporter is just a consumer of this feature, so I don't think we should put it there.

**Comment by arbulu89** [comment]
> @arbulu89 hmm... so i misunderstood your idea on #15
> I have already put the usage example in `drbd-formula` with/without a pacemaker, do you think the [drbd nfs j2 template file](https://github.com/SUSE/drbd-formula/blob/master/examples/with_pacemaker/drbd_with_nfs_crm.j2) is enough?
> 
> If so, we can close this and [SUSE/ha-sap-terraform-deployments#547](https://github.com/SUSE/ha-sap-terraform-deployments/pull/547)

If the templates are already shipped I think we are fine. The thing is that I didn't know that we were shipping the files in the `example` folder, until you pointed me that in the issue.

I think the unique missing piece is to update the `drbd_with_nfs_crm.j2` with the latest changes from [drbd_cluster.j2(https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/salt/drbd_node/files/templates/drbd_cluster.j2), remove the file from `ha-sap-terraform-deployments` as it would be duplicated, and change the [pillar.sls](https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/salt/drbd_node/files/templates/drbd_cluster.j2) to use the shipped template.

I think the `split-brain` script should belong to `ha-cluster-exporter`

**Comment by stefanotorresi** [comment]
> I think the `split-brain` script should belong to `ha-cluster-exporter`

Why do you think that? We don't have any reference to that script there, we only have a reference to an arbitrary file location check. The script is referenced here by the drbd configuration.

https://github.com/SUSE/drbd-formula/blob/484cfdd0b70ab3d505f1fb5e5e722e55dbb99545/pillar.example#L74-L75

https://github.com/SUSE/drbd-formula/blob/484cfdd0b70ab3d505f1fb5e5e722e55dbb99545/drbd/templates/global_common.j2#L48-L50

**Comment by arbulu89** [comment]
> > I think the `split-brain` script should belong to `ha-cluster-exporter`
> 
> Why do you think that? We don't have any reference to that script there, we only have a reference to an arbitrary file location check. The script is referenced here by the drbd configuration.
> 
> https://github.com/SUSE/drbd-formula/blob/484cfdd0b70ab3d505f1fb5e5e722e55dbb99545/pillar.example#L74-L75
> 
> https://github.com/SUSE/drbd-formula/blob/484cfdd0b70ab3d505f1fb5e5e722e55dbb99545/drbd/templates/global_common.j2#L48-L50

@stefanotorresi The script is named `notify-split-brain-haclusterexporter-suse-metric.sh`. That makes me think that is something for the ha-cluster-exporter. You can set whatever script as handler. This looks to be the one used by the exporter. That's why I think that it makes sense to have it there.

We are talking about: https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/salt/drbd_node/files/notify-split-brain-haclusterexporter-suse-metric.sh

**Comment by stefanotorresi** [comment]
> @stefanotorresi The script is named `notify-split-brain-haclusterexporter-suse-metric.sh`. That makes me think that is something for the ha-cluster-exporter. You can set whatever script as handler. This looks to be the one used by the exporter. That's why I think that it makes sense to have it there.

Then I think the problem is the script name, not its location. The actual script doesn't do anything specific for ha-cluster-exporter. It just writes a text file on an arbitrary location picked by convention.
The whole mechanism is meant to be a generic hook; while it was introduced to allow for the exporter to track such events, it should not be coupled to any specific consumer.

**Comment by arbulu89** [comment]
> Then I think the problem is the script name, not its location. The actual script doesn't do anything specific for ha-cluster-exporter. It just writes a text file on an arbitrary location picked by convention.
> The whole mechanism is meant to be a generic hook; while it was introduced to allow for the exporter to track such events, it should not be coupled to any specific consumer.

I don't really know if I follow you. This specific script was designed to notify exclusively the ha-cluster-exporter that a split brain happened. It is not used by anything else. This is what the script says in its documentation.
```
# the main goal of this handler signal via file when the splitbrain mechanism occurs.
# the handler create a simple file which is then tracked by the ha_cluster_exporter https://github.com/ClusterLabs/ha_cluster_exporter
# and from this file we create a metrics for detecting splitbrain and monitor it
# remember to remove the file once the drbd splitbrain is over, otherwise the exporter will always set the metric of splitbrain to present
```
So, if we don't ship this anywhere (now it's located in `ha-sap-terraform-deployments` project). How the users will use if they install the ha-cluster-exporter as a standalone project (without our deployment project)? As they might do in the Azure monitoring solution. I guess this metric won't work. `drbd-formula` doesn't know anything about the exporter at least.

**Edit**: In fact, it's even documented to get it from other project in [docs](https://github.com/ClusterLabs/ha_cluster_exporter/blob/master/doc/metrics.md#ha_cluster_drbd_split_brain). Wouldn't make more sense to have it there?

**Comment by nick-wang** [comment]
> I think the unique missing piece is to update the `drbd_with_nfs_crm.j2` with the latest changes from [drbd_cluster.j2(https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/salt/drbd_node/files/templates/drbd_cluster.j2), remove the file from `ha-sap-terraform-deployments` as it would be duplicated, and change the [pillar.sls](https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/salt/drbd_node/files/templates/drbd_cluster.j2) to use the shipped template.

If i adapt the [pillar.sls](https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/salt/drbd_node/files/templates/drbd_cluster.j2) without mentioning ha-sap-terraform-deployments project. I need to remove all the parameters related to `cloud provider` from {% set cloud_provider = grains['cloud_provider'] %}. which is quite similar to the provided one.
That is one of the reason why i want to use another folder point to the ha-sap-terraform-deployments project.

**Comment by stefanotorresi** [comment]
@arbulu89 uhm, I see where you're coming from now. :v: 
Well, as far as I was concerned this mechanism should've been advertised to be as generic as possible, but since we make those very specific references, I guess we'd rather just put it in the same repo. Ok for moving it, then. @MalloZup would you sign this off?

**Comment by nick-wang** [comment]
For `notify-split-brain-haclusterexporter-suse-metric.sh`, which must(and only) use together with DRBD and  `ha-cluster-exporter`. So i am fine to put it in `drbd-formula`, `ha-cluster-exporter` or `drbd-utils`, but not `ha-sap-terraform-deployments`.

If there is an examples or docs to integrate with other projects (to monitor) in `ha-cluster-exporter`. I think it is great to put there as a DRBD entry. Otherwise, it can put here or in `drbd-utils` and maintained by us. (However, i don't think upstream will accept this, so if the `ha-cluster-exporter` also target other distribution except SUSE, i would recommand release together with `ha-cluster-exporter`)
The split-brain handler with `ha-cluster-exporter` is bind to DRBD but not `drbd-formula`. User may still need this script without using drbd salt formula to install.

**Comment by stefanotorresi** [comment]
@nick-wang do you think we could implement something in drbd like another hook to signal that the split brain has been resolved?

**Comment by arbulu89** [comment]
> > I think the unique missing piece is to update the `drbd_with_nfs_crm.j2` with the latest changes from [drbd_cluster.j2(https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/salt/drbd_node/files/templates/drbd_cluster.j2), remove the file from `ha-sap-terraform-deployments` as it would be duplicated, and change the [pillar.sls](https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/salt/drbd_node/files/templates/drbd_cluster.j2) to use the shipped template.
> 
> If i adapt the [pillar.sls](https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/salt/drbd_node/files/templates/drbd_cluster.j2) without mentioning ha-sap-terraform-deployments project. I need to remove all the parameters related to `cloud provider` from {% set cloud_provider = grains['cloud_provider'] %}. which is quite similar to the provided one.
> That is one of the reason why i want to use another folder point to the ha-sap-terraform-deployments project.

@nick-wang We cannot remove the `grains['cloud_provider']` entry. The template won't know how to deal with the different cloud providers. Keep in mind that the template will be used by `habootstrap-formula`, and the formula will always put this grain. The thing is that this template could go in the `habootstrap-formula` project, but for business reasons we decided to put the templates in each of the other formulas.
If you want, I will create the changes myself and put you on review. I have quite clear what to do. And later on you can put your comments on it. What do you think?

**Comment by nick-wang** [comment]
> @nick-wang do you think we could implement something in drbd like another hook to signal that the split brain has been resolved?

@stefanotorresi  It will be prefect to have another hook to remove alert. But it will be much difficult than `split-brain` handler, since DRBD internal doesn't provide any event/hook when `split-brain` situation solved. I think it may rely on a daemon to monitor the status of DRBD.
Still ok (but not good enough) to leave as it is. Because `split-brain` handler only triggered when `split-brain` happened and can't be resolved automatically. In this case, need admin to check/fix manually. And pray the admin won't forget (and have knowledge) to remove the file after that...

**Comment by nick-wang** [comment]
> The thing is that this template could go in the `habootstrap-formula` project, but for business reasons we decided to put the templates in each of the other formulas.

OK, then i would prefer to have a seperate folder/file instead of modify the existed generic simple one(may not prefect in cloud). 

> If you want, I will create the changes myself and put you on review. I have quite clear what to do. And later on you can put your comments on it. What do you think?

Sure, I am fine with your change or new pr.

**Comment by MalloZup** [comment]
I'm ok to move it to the exporter.

The drbd split brain metric is unfortunately quite complex on its own. :( I wish we could get rid of that script somehow . perhaps is something we could handle better with alers + event-handler new project. we will see)

**Comment by nick-wang** [comment]
I think we can close this pull request. We can revisit this when necessary.

**Pull request closed without merging**
